/*
* Automatically generated by 'ng g ng-alain:plugin icon'
* @see https://ng-alain.com/cli/plugin#icon
*/

import {
  AlipayCircleOutline,
  AppstoreOutline,
  ArrowDownOutline,
  CloudOutline,
  CopyrightOutline,
  DingdingOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GithubOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  PayCircleOutline,
  PrinterOutline,
  ScanOutline,
  SettingOutline,
  StarOutline,
  TaobaoCircleOutline,
  TeamOutline,
  ToolOutline,
  UserOutline,
  WeiboCircleOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  AlipayCircleOutline,
  AppstoreOutline,
  ArrowDownOutline,
  CloudOutline,
  CopyrightOutline,
  DingdingOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GithubOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  PayCircleOutline,
  PrinterOutline,
  ScanOutline,
  SettingOutline,
  StarOutline,
  TaobaoCircleOutline,
  TeamOutline,
  ToolOutline,
  UserOutline,
  WeiboCircleOutline
];
