// Generated by https://quicktype.io

export interface ArticleInformation {
  articleSectionId:  string; // 板块的ID
  articleTitle:      string; // 文章标题
  articleContent:    string; // 文章的内容
  articleId:         string; // 文章ID
  articleLabels:     any; // 文章的标签
  userId:            number; // 用户ID
}
